# Generated by Django 2.1.3 on 2018-11-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181105_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='static')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='media_content',
            field=models.FileField(blank=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='static'),
        ),
    ]
