# Generated by Django 2.1.3 on 2018-11-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181112_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
