# Generated by Django 2.1.3 on 2018-11-16 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20181116_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='fileitem',
            old_name='timestamp',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='media_content',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='fileItem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.FileItem'),
        ),
        migrations.AddField(
            model_name='listarticle',
            name='article',
            field=models.ManyToManyField(to='blog.Article'),
        ),
    ]
