# Generated by Django 2.1.3 on 2018-11-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181116_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='file_type',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
