# Generated by Django 2.1.3 on 2018-11-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181127_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentaire',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='content',
            new_name='contenu',
        ),
    ]
