# Generated by Django 2.1.3 on 2018-11-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181127_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
